---
title: "Project"
author: "Kat Pinder,"
date: "2023-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(dplyr)
library(here)
library(naniar)
library(paletteer)
``` 

Load Dataset
```{r}
planets<-read_csv("data/cleaned_5250.csv")
```

```{r}
names(planets)
```

```{r}
miss_var_summary(planets)
```

```{r}
glimpse(planets)
```

Palette
```{r}
my_palette <- paletteer_d("palettetown::swampert")
```

Most common detection method
```{r}
planets%>%
  ggplot(aes(x=detection_method,fill=detection_method))+geom_bar()+theme(axis.text.x = element_text(angle = 60, hjust=1))+scale_fill_manual(values=my_palette)
```

Number of discoveries each year
```{r}
planets%>%
  ggplot(aes(x=discovery_year))+geom_bar()
#spike in 2014 and 2016, due to Kepler discoveries?
```

Number of discoveries each year of different planet types
```{r}
planets%>%
  ggplot(aes(x=discovery_year,fill=planet_type))+geom_bar()+facet_wrap(~planet_type)+scale_fill_manual(values=my_palette)+labs(title="Number of Detected Planets per Year by Planet Type",x="Discovery Year",y="Number of Planets Discovered",fill="Planet Type")
```

Number of discoveries each year by discovery method
```{r}
planets%>%
  ggplot(aes(x=discovery_year,fill=detection_method))+geom_bar()+labs(title="Number of Detected Planets per Year by Detection Method",x="Discovery Year",y="Number of Planets Discovered",fill="Detection Method")+scale_fill_manual(values=my_palette)
```

Ratio of Kepler-found planets in 2014

```{r}
planets%>%
  filter(discovery_year=="2014")
#875
```

```{r}
planets%>%
  filter(discovery_year=="2014")%>%
  filter(grepl('Kepler',name))
#787 so 787/875 roughly equals 90%
```

Ratio of Kepler-found planets in 2016
```{r}
planets%>%
  filter(discovery_year=="2016")
#1517
```

```{r}
planets%>%
  filter(discovery_year=="2016")%>%
  filter(grepl('Kepler',name))
#1283 so 1283/1517 is roughly 85%
```

2nd dataset
```{r}
planets2<-read_csv("data/oec.csv")
```

```{r}
names(planets2)
```

```{r}
miss_var_summary(planets2)
```

```{r}
glimpse(planets2)
```

Exoplanets within Habitable Temp Range
```{r}
planets2%>%
  select(PlanetIdentifier,SurfaceTempK,PeriodDays,PlanetaryMassJpt,RadiusJpt,PeriodDays,DistFromSunParsec,HostStarTempK)%>%
  filter(SurfaceTempK>=274.15&SurfaceTempK<=374.15)%>%
#Temp range is between 274.15-374.15 K which is derived from the temp range that water is in a liquid state, reveals 59 planets
  filter(PlanetaryMassJpt<=.005&PlanetaryMassJpt>=.001)
#Earth's planetary mass relative to Jupiter(PlanetaryMassJpt) is 0.003
```


